# Generated by Django 4.2 on 2023-04-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GI', 'Goals & Initiatives'), ('PS', 'Products & Services'), ('DI', 'Data & Information'), ('SA', 'Systems & Application'), ('NI', 'Networks & Infrastructure')], default='GI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.ForeignKey(default='GI', on_delete=django.db.models.deletion.CASCADE, to='ea3repository.level')),
            ],
        ),
    ]
