# Generated by Django 4.2 on 2023-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('GI', 'Goals and Initiatives'), ('PS', 'Products and Services'), ('DI', 'Data and Information'), ('SA', 'Systems and Application'), ('NI', 'Networks and Infrastructure')], default='GI', max_length=2),
        ),
    ]
