# Generated by Django 4.2 on 2023-04-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea3repository', '0002_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='level',
            field=models.ForeignKey(default='DI', on_delete=django.db.models.deletion.CASCADE, to='ea3repository.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('GI', 'Goals and Initiatives'), ('PS', 'Products and Services'), ('DI', 'Data and Information'), ('SA', 'Systems and Application'), ('NI', 'Networks and Infrastructure')], default='DI', max_length=2),
        ),
    ]
